enableTelemetry: 0

packageExtensions:
  "@vitejs/plugin-vue@*":
    dependencies:
      vite: 2.0.0-beta.56

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-2.4.0.cjs
